//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentiApp1
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Note
    {
        public int ID { get; set; }
        public int IDMaterie { get; set; }
        public int IDStudent { get; set; }
        public Nullable<short> Nota { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string TipExamen { get; set; }
    
        public virtual Materii Materii { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
