//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentiApp2
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Studenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studenti()
        {
            this.Note = new ObservableCollection<Note>();
        }
    
        public int ID { get; set; }
        public string NrMatricol { get; set; }
        public string Nume { get; set; }
        public string Adresa { get; set; }
        public string Oras { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> DataNasterii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Note> Note { get; set; }
    }
}
